language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --testsuite unit
  - php tests/benchmark/benchmark.php

cache:
  directories:
    - vendor/
